# edge/config.py
# Central configuration for the CrowdSense edge agent.
# Edit these values before running.

# ── Backend ──────────────────────────────────────────────────────────────────
BACKEND_URL   = "http://localhost:8080/api/v1"
LOCATION_ID   = "loc_001"          # Must match a row in the locations table

# ── MQTT (offline mesh) ───────────────────────────────────────────────────────
MQTT_BROKER   = "localhost"        # Mosquitto broker host (same LAN or localhost)
MQTT_PORT     = 1883
MQTT_TOPIC    = f"crowd/{LOCATION_ID}"
MQTT_ENABLED  = True               # Set False if Mosquitto is not installed

# ── Timing ───────────────────────────────────────────────────────────────────
CROWD_CAPTURE_INTERVAL_SECONDS = 5
SYNC_INTERVAL_SECONDS          = 30

# ── Crowd level thresholds (person count) ─────────────────────────────────────
ALERT_THRESHOLDS = {
    "LOW":      10,
    "MEDIUM":   25,
    "HIGH":     50,
    "CRITICAL": 75,
}

# ── Local storage ─────────────────────────────────────────────────────────────
SQLITE_DB_PATH = "data/crowdsense_local.db"

# ── Sensor mode ──────────────────────────────────────────────────────────────
# "SIMULATION"  – correlated random data (no hardware required)
# "DEMO_VIDEO"  – replay pre-processed video CSV (most realistic demo)
# "LIVE"        – real YOLOv8 + WiFi probe on Raspberry Pi
SENSOR_MODE = "DEMO_VIDEO"

# Path to pre-processed demo CSV (generated by generate_demo_data.py)
DEMO_CSV_PATH   = "demo_data/readings_cache.csv"
DEMO_SPEED_FACTOR = 1.0            # 1.0 = real speed, 2.0 = 2x faster

# ── Fusion weights (auto-adjusted if sensor goes offline) ────────────────────
CAMERA_WEIGHT = 0.65
WIFI_WEIGHT   = 0.35

# ── Local alert (internet-independent) ───────────────────────────────────────
LOCAL_ALERT_ENABLED   = True
GPIO_LED_PIN          = 17         # BCM pin for red LED (Pi only)
LOCAL_ALERT_UDP_PORT  = 5555       # Broadcast port for other Pi units on LAN